# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beerlot_db
    username: postgres
    password: adminadmin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

