spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/beerlot_db
    username: postgres
    password: adminadmin

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

  # GCP
  cloud:
    gcp:
      sql:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/

oauth:
  client:
    google:
      oauth-login-endpoint: https://accounts.google.com/o/oauth2/v2/auth
      oauth-token-endpoint: https://oauth2.googleapis.com/token
      backend-redirect-url: http://localhost:8080/api/v1/auth/login/google
      client-id: 916193052888-hivpf5e2nr4hld3r53q20i4evc8a2fod.apps.googleusercontent.com
      client-secret: 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
      state: ImmerMitBeerlot
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
      response_type: code
      grant_type: authorization_code


jwt:
  header: Authorization
  issuer: beerlot-server
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2OTc5NTMwOCwiaWF0IjoxNjY5Nzk1MzA4fQ.-T8qSGFVfSrRZkDL82LQY2_RX4mi2ntM5bZnDTbxoZEaipM15jjuCJrtXkssHWrmYIs3rUxO4pqzqDsNb_-UOw
  access-token-expiry-in-seconds: 86400
  refresh-token-expiry-in-seconds: 1296000

app:
  redirect:
    signup: https://beerlot-client.vercel.app/signup
    after-login: https://beerlot-client.vercel.app
