spring:
  config:
    import: secret-local.yml

# Database
  datasource:
    url: jdbc:postgresql://localhost:5432/beerlot_db
    username: postgres
    password: adminadmin

# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

# GCP
  cloud:
    gcp:
      sql:
        enabled: false

app:
  redirect-url: https://beerlot-client.vercel.app
