spring:
  config:
    import:
      - secret/prod/application-cloud-prod.yml
      - secret/prod/application-oauth-prod.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect