spring:
  config:
    import:
    - secret/local/application-cloud-local.yml
    - secret/local/application-oauth-local.yml

# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

