spring:
  config:
    import:
      - secret/dev/application-db-dev.yml
      - secret/dev/application-oauth-dev.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
