name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        default: 'dev'
        required: true

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  job_information:
    name: 'Job Information'
    runs-on: ubuntu-latest
    steps:
      - name: 'Start Job Information'
        run: |
          echo "CD workflow"
          echo "Selected branch: " ${{ github.ref_name }}
          echo "Selected environment: " ${{ inputs.environment }}

  deploy:
    name: 'Build Docker Image & Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Authorize to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authorize to Docker Repository
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Test and Build
        run: |
          cd beerlot-core
          ./gradlew clean build

      - name: Build Docker Image
        run: |
          cd beerlot-core
          docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/beerlot-core-repository/beerlot-core:latest .

      - name: Push to Artifact Repository
        run:
          docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/beerlot-core-repository/beerlot-core:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy beerlot-core \
            --region asia-northeast1 \
            --image asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/beerlot-core-repository/beerlot-core:latest \
