name: CD

on:
  workflow_dispatch:
    environment:
        description: 'Environment'
        type: environment
        default: 'develop'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Authorize to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          #token_format: 'access_token'
          #service_account: ${{ secrets.GCP_SA_DEPLOY }}
          #workload_identity_provider: ${{ secrets.GCP_WI_PROVIDER }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authorize to Docker Repository
        #uses: 'docker/login-action@v1'
        #with:
          #username: 'oauth2accesstoken'
          #password: ${{ steps.auth.outputs.access_token }}
          #registry: 'asia-northeast1-docker.pkg.dev'
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          cd beerlot-core
          ./gradlew clean build

      - name: Push to Artifact Repository
        run: |
          cd beerlot-core
          docker build -t asia-northeast1-docker.pkg.dev/beerlot-dev-363211/beerlot-core-repository/beerlot-core:latest .
          docker push asia-northeast1-docker.pkg.dev/beerlot-dev-363211/beerlot-core-repository/beerlot-core:latest
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy beerlot-core \
            --region asia-northeast1 \
            --image asia-northeast1-docker.pkg.dev/beerlot-dev-363211/bbeerlot-core-repository/beerlot-core:latest \

        #uses: google-github-actions/deploy-cloudrun@v0
        #with:
          #service: beerlot-core
          #region: asia-northeast1
          # NOTE: If using a pre-built image, update the image name here
          #image: asia-northeast1-docker.pkg.dev/beerlot-dev/beerlot-core-image/beerlot-core:latest