name: CD

on:
  workflow_dispatch:
    environment:
        description: 'Environment'
        type: environment
        default: 'develop'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Authorize to GCP
        uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.DEPLOY_SA }}

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew clean build
