name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  job_information:
    name: 'Job Information'
    runs-on: ubuntu-latest
    steps:
      - name: 'Start Job Information'
        run: |
          echo "CI workflow"
          echo "Selected branch: " ${{ github.ref_name }}

  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

  test_and_build:
    name: 'Test & Build'
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Test and Build
        run: |
          cd beerlot-core
          ./gradlew clean build
