name: Terraform Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: dev
    env:
      environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Authorize to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: beerlot-api/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: beerlot-api/terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: beerlot-api/terraform
        run: terraform plan -out=tfplan -input=false \
          -var-file=environments/${{ env.environment }}.tfvars \
          -var="project=${{ secrets.GCP_PROJECT }}"

      - name: Terraform Apply
        working-directory: beerlot-api/terraform
        run: terraform apply -auto-approve