name: Deploy API on DEV

on:
  push:
    branches:
      - develop
      - fix

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  job_information:
    name: 'Job Information'
    runs-on: ubuntu-latest
    steps:
      - name: 'Start Job Information'
        run: |
          echo "CD workflow"
          echo "Selected branch: " ${{ github.ref_name }}
          echo "Selected environment: " ${{ inputs.environment }}

  deploy:
    name: 'Build Docker Image & Deploy'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Authorize to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authorize to Docker Repository
        run: gcloud auth configure-docker

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Test and Build
        run: |
          cd beerlot-api
          ./gradlew clean build

      - name: Build Docker Image
        run: |
          cd beerlot-api
          docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/beerlot-api-image:${{ github.sha }} -f Dockerfile-dev .

      - name: Push to Artifact Repository
        run:
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/beerlot-api-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy beerlot-api \
            --region ${{ secrets.GCP_REGION }} \
            --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/beerlot-api-image:${{ github.sha }} \
            --cpu 1 \
            --memory 1024Mi
